### ISSUE TITLE
Option bBoot=0 (uses optimal block-length) does not work

### ISSUE THREAD

**Issue by Segbe** [ArdiaD/PeerPerformance#10]
Hello,

I'm trying to use the following function but it does not work. The same happens for the other function also. Here is an illustration.

This work
require(PeerPerformance)
sharpeScreening(matrix(rnorm(1000),10), control = list(nCore = 4, type = 2, hac = TRUE,bBoot=2))

But this those not work
sharpeScreening(matrix(rnorm(1000),10), control = list(nCore = 4, type = 2, hac = TRUE,bBoot=0))

#Message: Error in sample.int(T, size = l, replace = TRUE) :  vector size cannot be infinite

**Comment by ArdiaD** [comment]
the block size must be at least 1
